spring:
  datasource:
    url: jdbc:mysql://localhost:3306/UEED_DB
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
